<?php

// AUTO-GENERATED by convert_cards.php — do not edit manually
// Source: docs/cards.csv

// Icon constants
define('ICON_DRIVE', 'drive');
define('ICON_MUSCLE', 'muscle');
define('ICON_DISGUISE', 'disguise');
define('ICON_KEY', 'key');

// Card type constants
define('TYPE_MONEY', 'money');
define('TYPE_AGENT', 'agent');
define('TYPE_TECH', 'tech');
define('TYPE_PLOT', 'plot');
define('TYPE_BASE', 'base');
define('TYPE_MISSION', 'mission');

function get_icon_label(string $icon): string {
    $map = [
        ICON_DRIVE => '🚘',
        ICON_MUSCLE => '💪',
        ICON_DISGUISE => '🥸',
        ICON_KEY => '🔑',
    ];
    return $map[$icon] ?? $icon;
}

function get_card_catalog(): array {
    return [
        'money_1' => [
            'id' => 'money_1',
            'name' => '$1',
            'type' => 'money',
            'tier' => 0,
            'cost' => 0,
            'value' => 1,
            'stars' => 0,
            'description' => '$1',
        ],
        'money_2' => [
            'id' => 'money_2',
            'name' => '$2',
            'type' => 'money',
            'tier' => 0,
            'cost' => 0,
            'value' => 2,
            'stars' => 0,
            'description' => '$2',
        ],
        'money_3' => [
            'id' => 'money_3',
            'name' => '$3',
            'type' => 'money',
            'tier' => 0,
            'cost' => 0,
            'value' => 3,
            'stars' => 0,
            'description' => '$3',
        ],
        'safehouse' => [
            'id' => 'safehouse',
            'name' => 'Safehouse',
            'type' => 'base',
            'tier' => 0,
            'stars' => 0,
            'cost' => 0,
            'indestructible' => true,
            'description' => 'Can host an Agent. Indestructible.',
        ],
        'hideaway' => [
            'id' => 'hideaway',
            'name' => 'Hideaway',
            'type' => 'base',
            'tier' => 0,
            'stars' => 0,
            'cost' => 0,
            'indestructible' => false,
            'description' => 'Can host an Agent.',
        ],
        'fundraising' => [
            'id' => 'fundraising',
            'name' => 'Fundraising',
            'type' => 'mission',
            'tier' => 0,
            'stars' => 0,
            'cost' => 0,
            'requirements' => ['any'],
            'value' => 0,
            'gems' => 1,
            'always_available' => true,
            'description' => 'Requires: ❓ — Reward: . Always available.',
        ],
        'alley_getaway' => [
            'id' => 'alley_getaway',
            'name' => 'Alley Getaway',
            'type' => 'mission',
            'tier' => 1,
            'stars' => 0,
            'cost' => 0,
            'requirements' => ['drive', 'muscle'],
            'value' => 3,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🚘💪 — Reward: $3',
        ],
        'train_hijinx' => [
            'id' => 'train_hijinx',
            'name' => 'Train Hijinx',
            'type' => 'mission',
            'tier' => 2,
            'stars' => 1,
            'cost' => 0,
            'requirements' => ['drive', 'drive', 'drive', 'disguise'],
            'value' => 4,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🚘🚘🚘🥸 — Reward: 1⭐ $4',
        ],
        'halo_drop' => [
            'id' => 'halo_drop',
            'name' => 'HALO Drop',
            'type' => 'mission',
            'tier' => 3,
            'stars' => 4,
            'cost' => 0,
            'requirements' => ['drive', 'drive', 'drive', 'drive', 'drive', 'key', 'key'],
            'value' => 0,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🚘🚘🚘🚘🚘🔑🔑 — Reward: 4⭐',
        ],
        'arm_wrestling' => [
            'id' => 'arm_wrestling',
            'name' => 'Arm Wrestling',
            'type' => 'mission',
            'tier' => 1,
            'stars' => 0,
            'cost' => 0,
            'requirements' => ['muscle', 'disguise'],
            'value' => 4,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 💪🥸 — Reward: $4',
        ],
        'fencing_duel' => [
            'id' => 'fencing_duel',
            'name' => 'Fencing Duel',
            'type' => 'mission',
            'tier' => 2,
            'stars' => 1,
            'cost' => 0,
            'requirements' => ['muscle', 'muscle', 'muscle', 'key'],
            'value' => 5,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 💪💪💪🔑 — Reward: 1⭐ $5',
        ],
        'rooftop_showdown' => [
            'id' => 'rooftop_showdown',
            'name' => 'Rooftop Showdown',
            'type' => 'mission',
            'tier' => 3,
            'stars' => 4,
            'cost' => 0,
            'requirements' => ['muscle', 'muscle', 'muscle', 'muscle', 'muscle', 'drive', 'drive'],
            'value' => 0,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 💪💪💪💪💪🚘🚘 — Reward: 4⭐',
        ],
        'convent_secrets' => [
            'id' => 'convent_secrets',
            'name' => 'Convent Secrets',
            'type' => 'mission',
            'tier' => 1,
            'stars' => 0,
            'cost' => 0,
            'requirements' => ['disguise', 'key'],
            'value' => 5,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🥸🔑 — Reward: $5',
        ],
        'traveling_troupe' => [
            'id' => 'traveling_troupe',
            'name' => 'Traveling Troupe',
            'type' => 'mission',
            'tier' => 2,
            'stars' => 1,
            'cost' => 0,
            'requirements' => ['disguise', 'disguise', 'disguise', 'drive'],
            'value' => 6,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🥸🥸🥸🚘 — Reward: 1⭐ $6',
        ],
        'megastar_machinations' => [
            'id' => 'megastar_machinations',
            'name' => 'Megastar Machinations',
            'type' => 'mission',
            'tier' => 3,
            'stars' => 4,
            'cost' => 0,
            'requirements' => ['disguise', 'disguise', 'disguise', 'disguise', 'disguise', 'muscle', 'muscle'],
            'value' => 0,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🥸🥸🥸🥸🥸💪💪 — Reward: 4⭐',
        ],
        'gate_hacking' => [
            'id' => 'gate_hacking',
            'name' => 'Gate Hacking',
            'type' => 'mission',
            'tier' => 1,
            'stars' => 0,
            'cost' => 0,
            'requirements' => ['key', 'drive'],
            'value' => 4,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🔑🚘 — Reward: $4',
        ],
        'retinal_scan' => [
            'id' => 'retinal_scan',
            'name' => 'Retinal Scan',
            'type' => 'mission',
            'tier' => 2,
            'stars' => 1,
            'cost' => 0,
            'requirements' => ['key', 'key', 'key', 'muscle'],
            'value' => 5,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🔑🔑🔑💪 — Reward: 1⭐ $5',
        ],
        'embassy_safe' => [
            'id' => 'embassy_safe',
            'name' => 'Embassy Safe',
            'type' => 'mission',
            'tier' => 3,
            'stars' => 4,
            'cost' => 0,
            'requirements' => ['key', 'key', 'key', 'key', 'key', 'disguise', 'disguise'],
            'value' => 0,
            'gems' => 0,
            'always_available' => false,
            'description' => 'Requires: 🔑🔑🔑🔑🔑🥸🥸 — Reward: 4⭐',
        ],
        'sword_cane' => [
            'id' => 'sword_cane',
            'name' => 'Sword-cane',
            'type' => 'tech',
            'tier' => 1,
            'stars' => 0,
            'cost' => 4,
            'icons' => [['muscle', 'disguise']],
            'description' => '💪/🥸 ($4)',
        ],
        'bazooka' => [
            'id' => 'bazooka',
            'name' => 'Bazooka',
            'type' => 'tech',
            'tier' => 2,
            'stars' => 0,
            'cost' => 7,
            'icons' => ['muscle', 'muscle'],
            'description' => '💪💪 ($7)',
        ],
        'ram' => [
            'id' => 'ram',
            'name' => 'Ram',
            'type' => 'tech',
            'tier' => 1,
            'stars' => 0,
            'cost' => 4,
            'icons' => [['drive', 'key']],
            'description' => '🚘/🔑 ($4)',
        ],
        'holo_projector' => [
            'id' => 'holo_projector',
            'name' => 'Holo-projector',
            'type' => 'tech',
            'tier' => 2,
            'stars' => 0,
            'cost' => 8,
            'icons' => ['disguise', 'disguise'],
            'description' => '🥸🥸 ($8)',
        ],
        'muscle' => [
            'id' => 'muscle',
            'name' => 'Muscle',
            'type' => 'agent',
            'tier' => 1,
            'stars' => 0,
            'cost' => 3,
            'max_tech' => 1,
            'icons' => ['muscle'],
            'always_available' => true,
            'description' => '💪 — Always available ($3)',
        ],
        'shadow' => [
            'id' => 'shadow',
            'name' => 'Shadow',
            'type' => 'agent',
            'tier' => 1,
            'stars' => 0,
            'cost' => 4,
            'max_tech' => 1,
            'icons' => ['disguise'],
            'always_available' => true,
            'description' => '🥸 — Always available ($4)',
        ],
        'doorkicker' => [
            'id' => 'doorkicker',
            'name' => 'Doorkicker',
            'type' => 'agent',
            'tier' => 2,
            'stars' => 0,
            'cost' => 5,
            'max_tech' => 1,
            'icons' => ['muscle', 'key'],
            'always_available' => false,
            'description' => '💪🔑 ($5)',
        ],
        'reputable_driver' => [
            'id' => 'reputable_driver',
            'name' => 'Reputable Driver',
            'type' => 'agent',
            'tier' => 2,
            'stars' => 0,
            'cost' => 5,
            'max_tech' => 1,
            'icons' => ['disguise', 'drive'],
            'always_available' => false,
            'description' => '🥸🚘 ($5)',
        ],
        'speedboat_mechanic' => [
            'id' => 'speedboat_mechanic',
            'name' => 'Speedboat Mechanic',
            'type' => 'agent',
            'tier' => 3,
            'stars' => 0,
            'cost' => 7,
            'max_tech' => 2,
            'icons' => ['muscle', 'muscle', 'drive'],
            'always_available' => false,
            'description' => '💪💪🚘 ($7)',
        ],
        'hoodied_hacker' => [
            'id' => 'hoodied_hacker',
            'name' => 'Hoodied Hacker',
            'type' => 'agent',
            'tier' => 3,
            'stars' => 0,
            'cost' => 8,
            'max_tech' => 2,
            'icons' => ['key', 'key', 'disguise'],
            'always_available' => false,
            'description' => '🔑🔑🥸 ($8)',
        ],
        'burn_notice' => [
            'id' => 'burn_notice',
            'name' => 'Burn Notice',
            'type' => 'plot',
            'tier' => 2,
            'stars' => 0,
            'cost' => 4,
            'effect' => 'trash',
            'description' => 'Trash a card from your play, discard, or hand areas ($4)',
        ],
        'paperwork' => [
            'id' => 'paperwork',
            'name' => 'Paperwork',
            'type' => 'plot',
            'tier' => 2,
            'stars' => 0,
            'cost' => 5,
            'effect' => 'paperwork',
            'description' => 'Every other player gains a Red Tape ($5)',
        ],
        'para_drop' => [
            'id' => 'para_drop',
            'name' => 'Para-drop',
            'type' => 'plot',
            'tier' => 2,
            'stars' => 0,
            'cost' => 6,
            'effect' => 'draw2',
            'description' => 'Draw two cards ($6)',
        ],
        'red_tape' => [
            'id' => 'red_tape',
            'name' => 'Red Tape',
            'type' => 'plot',
            'tier' => 0,
            'stars' => 0,
            'cost' => 0,
            'effect' => 'none',
            'description' => 'Does nothing',
        ],
        'multitasking' => [
            'id' => 'multitasking',
            'name' => 'Multitasking',
            'type' => 'plot',
            'tier' => 2,
            'stars' => 0,
            'cost' => 6,
            'effect' => 'multitask',
            'description' => 'You may complete an additional mission this turn ($6)',
        ],
        'training_procedure' => [
            'id' => 'training_procedure',
            'name' => 'Training Procedure',
            'type' => 'plot',
            'tier' => 2,
            'stars' => 0,
            'cost' => 6,
            'effect' => 'training',
            'description' => 'Trash an agent from your hand to gain an agent costing up to $3 more from the market ($6)',
        ],
    ];
}

function build_market_deck(): array {
    $deck = [];
    $market_cards = [
        'sword_cane' => 4,
        'bazooka' => 2,
        'ram' => 4,
        'holo_projector' => 2,
        'doorkicker' => 6,
        'reputable_driver' => 6,
        'speedboat_mechanic' => 6,
        'hoodied_hacker' => 6,
        'burn_notice' => 4,
        'paperwork' => 4,
        'para_drop' => 4,
        'multitasking' => 4,
        'training_procedure' => 4,
    ];
    foreach ($market_cards as $id => $count) {
        for ($i = 0; $i < $count; $i++) {
            $deck[] = $id;
        }
    }
    shuffle($deck);
    return $deck;
}

function build_mission_decks(): array {
    $missions = [
        1 => [
            'alley_getaway' => 4,
            'arm_wrestling' => 4,
            'convent_secrets' => 4,
            'gate_hacking' => 4,
        ],
        2 => [
            'train_hijinx' => 4,
            'fencing_duel' => 4,
            'traveling_troupe' => 4,
            'retinal_scan' => 4,
        ],
        3 => [
            'halo_drop' => 2,
            'rooftop_showdown' => 2,
            'megastar_machinations' => 2,
            'embassy_safe' => 2,
        ],
    ];
    $decks = [];
    foreach ($missions as $tier => $cards) {
        $deck = [];
        foreach ($cards as $id => $count) {
            for ($i = 0; $i < $count; $i++) {
                $deck[] = $id;
            }
        }
        shuffle($deck);
        $decks[$tier] = $deck;
    }
    return $decks;
}

function get_starter_deck(): array {
    $deck = [];
    for ($i = 0; $i < 5; $i++) $deck[] = 'money_1';
    $deck[] = 'barnstormer';
    $deck[] = 'barnstormer';
    $deck[] = 'red_tape';
    $deck[] = 'red_tape';
    $deck[] = 'red_tape';
    shuffle($deck);
    return $deck;
}
